#!/bin/bash

cat << EOF

          _ __   __              ___      __           
   ____  (_) /__/ /_____        / (_)____/ /____  _____
  / __ \/ / //_/ __/ __ \______/ / / ___/ __/ _ \/ ___/
 / / / / / ,< / /_/ /_/ /_____/ / (__  ) /_/  __/ /    
/_/ /_/_/_/|_|\__/\____/     /_/_/____/\__/\___/_/     
  Nikto web server scanner + multple targets scan                                                       
		Developed by CyberGuy


EOF

help() {

   printf "
================================================================

\e[32m[\e[0m\e[31musage\e[0m\e[32m]:\e[0m

\e[31m-h\e[0m \e[32m==>\e[0m \e[31mHelp Menue\e[0m

\e[31m-l\e[0m \e[32m==>\e[0m \e[31mTargets List\e[0m

NOTE: you should have Nikto installed in your machine :)
================================================================

"
}

list=$1

if [[ -z ${list} ]];then

help
exit

fi

while getopts "l:h" option;

do case $option in

h)

help

exit

;;

l)

file=$OPTARG


;;

esac

done

if [[ $file ]];then

for target in $(cat $file);do

nikto -host $target | tee nikto-all.txt

printf "\n\n\n[============================[Working in next target]===============================]\n\n\n"

done
fi
